# Generated by Django 5.2.4 on 2025-07-31 23:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('merchant', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Rent', 'Rent'), ('Bills', 'Bills'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='Other', max_length=20)),
                ('reimbursable', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_currency', models.CharField(choices=[('YER', 'YER'), ('USD', 'USD')], default='YER', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('invoice', models.FileField(blank=True, help_text='Upload invoice (JPG/PNG)', null=True, upload_to='expenses/invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='User.user')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
